### ISSUE TITLE
Warning when building project in Eclipse

### ISSUE THREAD

**Issue by gabrielwalt** [Adobe-Marketing-Cloud/aem-project-archetype#4]
In the AEM Developer Tools, when starting a `Run as` > `Maven install`, then following warning is displayed in the `Problems` panel:
```
Description: No grammar constraints (DTD or XML Schema) referenced in the document.
Resource:    TEST-org.myorg.example.core.impl.TestHelloServiceImpl.xml
Path:        /example.core/target/surefire-reports
Location:    line 1
Type:        XML Problem
```

**Comment by rombert** [comment]
This one is simply warning us that our XML files don't specify a schema. Well, have no intention to do that.

The question is what can we do ... one possibility is to turn off the XML validation per-project when generating them inside Eclipse.

**Comment by rombert** [comment]
It seems there is another mechanism, in the Validation preferences we can configure the XML validator to not be executed for certain project natures. It would be good to make use of that.

![exclude-project-nature](https://cloud.githubusercontent.com/assets/21237/6300133/6b80a5cc-b92f-11e4-909d-871dc44db3ff.png)

**Comment by rombert** [comment]
This issue has been fixed in the Sling IDE Tooling project ( see [SLING-4450: Configure the XML validator to not run for content projects](https://issues.apache.org/jira/browse/SLING-4450) ) and will be incorporated in the next AEM Developer Tools public release.

If you'd like to build a fix yourself, please follow the instructions from [Sling IDE Tooling - building from source](https://sling.apache.org/documentation/development/ide-tooling.html#building-from-source).
