### ISSUE TITLE
Advantages of using clientlib-all instead of single category to unify clientlibs.

### ISSUE THREAD

**Issue by MuriloDAG** [Adobe-Marketing-Cloud/aem-project-archetype#50]
I was looking at the clientlib-all and it seems to create a problem: every time a new component (with clientlib) is created, it is required to explicitly add in there. 
I understand this gives flexibility to import the files in order.
I want to know if this gives anymore advantages when compared with putting all the components clientlibs in the same category.

**Comment by insideaem** [comment]
Hi,

I am also curious to know what is the reason behind that. I usually assign my component related clientlibs two categories, a general one like <project>.component and a specific one like <project>.textimage. Whenever I need to enforce file order, then I use the specific clientlib name in the dependency property. But in my clientlib.all I'll just embed every clientlib that has the category <project>.component.

Cheers,

**Comment by rombert** [comment]
I'm not really a frontend expert so maybe @eglistefan or @gabrielwalt remember the reasoning behind this

**Comment by gabrielwalt** [comment]
The idea is that when going live, one probably should explicitly list the exact clientlibs that are to be included, in order to make sure that only what's actually needed is loaded, and to make it more robust, because the order and content is then clearly defined.

For development it is certainly more convenient to use a global category name instead, so that the clientlib that embeds everything doesn't have to be edited each time that a new component is created.

But for this archetype, in order to promote best practice, I'd actually keep it as it is, and let it as a task to the developer to change this if desired, but that developer is then also encouraged to making sure that this gets reverted that prior to going live.
