### ISSUE TITLE
SimpleServlet not working

### ISSUE THREAD

**Issue by murilodag** [Adobe-Marketing-Cloud/aem-project-archetype#51]
I don't think that SimpleServlet is working.
I can't find the text it is supposed to output at the page.

Could you please re check this?
If it does work for you, could you tell me where did you find the outputted text and AEM version?

Thanks

**Comment by rombert** [comment]
@gabrielwalt  - you last touched this class in b9452c675427737a27deb1d1dd9f13c325416941, which includes

> Fixed SimpleServlet resource type 

Do you recall how is this supposed to work? Since the resource type for the servlet is `{appsFolderName}/structure/page` and the actual pages are of type `{appsFolderName}/component/structure/page` it's not intended to be used for the built-in pages.

**Comment by rombert** [comment]
Fixed with e493d009031398334a49b597e493ca7d73e398de
