### ISSUE TITLE
What is the purpose of the ui.content subproject? how do you prevent it from overwriting author generated content?

### ISSUE THREAD

**Issue by pmminov** [Adobe-Marketing-Cloud/aem-project-archetype#65]
Hi, just that small question I have

I just noticed that if an author creates a page via WCM/CRXDE i won't have those changes in my codebase, and hence I run into the risk of replacing that content whenever I deploy the whole project.

Could someone tell me whats the goal of it? Is there a setting/flag for when I want to deploy to Staging/Production environments? Or does this assume that I will be building a package manually that DOES NOT include /content?

**Comment by rombert** [comment]
In my (limited) experience with managing content, this can be considered a "seed" package, used to generate the filters for the content structure. You'll only deploy this once on a staging/production environment, otherwise - as you pointed out - will overwrite content.

However, you'll use this lots of times on a development environment, and also to replicate changes from author to publish in staging/prod and also to bring content from prod to staging if needed.
